include "potentially_dangerous/vigilantx_potentially_dangerous_java_DangerousFileManipulation.yar"
include "potentially_dangerous/vigilantx_potentially_dangerous_java_Dangerous_Class_Loading.yar"
include "potentially_dangerous/vigilantx_potentially_dangerous_java_Dangerous_ProcessBuilder.yar"
include "potentially_dangerous/vigilantx_potentially_dangerous_java_Dangerous_Reflection.yar"
include "potentially_dangerous/vigilantx_potentially_dangerous_java_Dangerous_Socket_Connection.yar"
include "potentially_dangerous/vigilantx_potentially_dangerous_java_Runtime_Exec.yar"

