include "rules/vigilantx/file_detect/java/index.yar"

include "rules/vigilantx/file_detect/file_detect_magic.yara"
include "rules/vigilantx/file_detect/file_detect_magic_CHROMIUM.yara"
include "rules/vigilantx/file_detect/file_detect_magic_PYTHON.yara"
include "rules/vigilantx/file_detect/file_detect_magic_STEAM.yara"
include "rules/vigilantx/file_detect/file_detect_magic_WINRAR.yara"
include "rules/vigilantx/file_detect/file_detect_magic_MINIX.yara"
include "rules/vigilantx/file_detect/file_detect_magic_GNU.yara"
include "rules/vigilantx/file_detect/file_detect_magic_iso.yara"
include "rules/vigilantx/file_detect/file_detect_magic_gpg.yara"
include "rules/vigilantx/file_detect/vigilantx_file_detect_magic_Inno_Setup_idska32.yara"
include "rules/vigilantx/file_detect/vigilantx_file_detect_magic_UNKNOWN_F1C50102.yara"
include "rules/vigilantx/file_detect/vigilantx_file_detect_magic_UNKNOWN.yara"
