include "rules/vigilantx/index.yar"
include "rules/anyrun/index.yar"
include "rules/nsfocusglobal/index.yar"
include "rules/virustotal/index.yar"
include "rules/kaspersky/index.yar"
include "rules/mirai/index.yar"
include "rules/elastic/index.yar"
include "rules/AlienVault-Labs/index.yar"
